spring:
  application:
    name: issue-tracker

# Kafka Setting
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: cs-group # Consumer Group ID
      auto-offset-reset: earliest # Read from first
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      redis:
        index-name: "cs-issue-idx" # data repository name
        prefix: "issue" # data key prefix
        initialize-schema: true

  # Redis connect setting
  data:
    redis:
      host: localhost
      port: 6379
      # password: # no password in local



logging:
  level:
    com.cstracker.issuetracker: DEBUG
    org:
      apache.kafka: INFO
      springframework.kafka: INFO

